### ISSUE TITLE
No such file or directory error running latest version

### ISSUE THREAD

**Issue by amahfouz** [hounshell/gulp-javac#2]
Tried this in latest version of node (7.1.0) as well as in 4.0.0 and gulp 3.9.1. Each time starting from scratch and installing the plugin.

The simplest javac and jar combination fails with an error indicating that the jar folder does not exist. After a bit of investigation, it seems that the 'tmp' modules manages to delete the folder before it is used by the javac task, somehow. 

See the trace from execution below:

[11:56:06] Using gulpfile ~/code/qortoba/gulpfile.js
[11:56:06] Starting 'javac-tools'...
[11:56:06] javac: Created javac task
[11:56:06] javac: Adding library: 
[11:56:06] jar: Created jar task
[11:56:06] Finished 'javac-tools' after 11 ms
[11:56:06] javac: javac Library stream complete
[11:56:06] javac: Source file: /Users/amahfouz/code/qortoba/src/android/com/mahfouz/qortoba/tools/GenJavaQortobaProxy.java
[11:56:06] javac: Source File Path: /var/folders/fp/wqc1qz9x1y1gdtkhf9z5zc6m0000gn/T/tmp-56623q3J1DoGxVttw.tmp
[11:56:06] javac: Argument File Path: /var/folders/fp/wqc1qz9x1y1gdtkhf9z5zc6m0000gn/T/tmp-56623WrJ5BbTVO3Sa.tmp
[11:56:06] javac: javac Executing: javac
[11:56:07] javac: javac javac complete; code: 0
[11:56:07] jar: Created folder: /var/folders/fp/wqc1qz9x1y1gdtkhf9z5zc6m0000gn/T/javac56623j9DWpZhIgGNJ
[11:56:07] jar: Creating jar: /var/folders/fp/wqc1qz9x1y1gdtkhf9z5zc6m0000gn/T/javac56623j9DWpZhIgGNJ/build/java/qortoba-tools.jar
[11:56:07] jar: Executing: jar [ 'cfv',
  '/var/folders/fp/wqc1qz9x1y1gdtkhf9z5zc6m0000gn/T/javac56623j9DWpZhIgGNJ/build/java/qortoba-tools.jar',
  '-C',
  '/var/folders/fp/wqc1qz9x1y1gdtkhf9z5zc6m0000gn/T/tmp-56623O4U9Jg2W1irl/',
  'com/mahfouz/qortoba/android/tools/GenJavaQortobaProxy.class' ]
[11:56:07] jar: java.io.FileNotFoundException: /var/folders/fp/wqc1qz9x1y1gdtkhf9z5zc6m0000gn/T/javac56623j9DWpZhIgGNJ/build/java/qortoba-tools.jar (No such file or directory)
[11:56:07] jar: 
[11:56:07] jar: 	at java.io.FileOutputStream.open0(Native Method)
[11:56:07] jar: 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
[11:56:07] jar: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[11:56:07] jar: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
[11:56:07] jar: 	at sun.tools.jar.Main.run(Main.java:195)
[11:56:07] jar: 	at sun.tools.jar.Main.main(Main.java:1288)
[11:56:07] jar: 
[11:56:07] jar: jar complete; code: 1
(node:56623) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, stat '/var/folders/fp/wqc1qz9x1y1gdtkhf9z5zc6m0000gn/T/javac56623j9DWpZhIgGNJ/build/java/qortoba-tools.jar'
(node:56623) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by hounshell** [comment]
Thanks for the report. Is this with the single task, or separate javac and
jar tasks?

**Comment by hounshell** [comment]
Oh the problem might be slashes in the jar name. I never tried it with
slashes, and I could easily see it failing on that. The error is on the jar
task's temp folder too, not the javac one, so even more likely.

**Comment by amahfouz** [comment]
Yes, it is on the jar task.

So you mean that the jar should not be in a sub-folder?

By the way, I could not run the combined task since it fails on addLibraries(). I will add that as another issue.

**Comment by hounshell** [comment]
Yeah, try a filename without any folders on it. I'll document the
addLibraries better too.

**Comment by amahfouz** [comment]
Yes, it works without the slashes. Do you think you will get to fixing it or should I work around it?

**Comment by hounshell** [comment]
It should be up in around 12 hours.

**Comment by amahfouz** [comment]
Thanks!

**Comment by hounshell** [comment]
I had a spare minute.  Fixed. 0.1.9

**Comment by amahfouz** [comment]
Great! Thanks.
