### ISSUE TITLE
Cannot use this in my gulpfile

### ISSUE THREAD

**Issue by bduff9** [hounshell/gulp-javac#4]
I have a current project where I need to be able to compile a couple jar files from a Java project using a node script.  I saw this project and with some prior experience in gulp, thought it would be perfect.  However, it does not work in my script, nor in a plain, vanilla gulpfile.

It seems like it uses newer JS features such as default parameter values and object spread, neither of which pass initial compilation.  I also tried using the newer gulpfile.babel.js with babel preset stage 0, however this does not help.  Just wondering how you are using it or what I might be doing wrong.  Here are the associated errors.

First when running it from my node script:
```
C:\mpower-build\node_modules\gulp-javac\javac.js:37
  var javac = function({
                       ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\mpower-build\gulpfile.babel.js:4:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

And then when running it from my gulpfile.babel.js:
```
[16:38:14] Requiring external module babel-register
C:\mpower-build\node_modules\gulp-javac\javac.js:29
    return function(...message) {
                    ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\mpower-build\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:/mpower-build/gulpfile.babel.js:4:15)
    at Module._compile (module.js:409:26)
```

I would be happy to provide any additional information.  Thanks!

**Comment by hounshell** [comment]
This is the first I know of it being used on Windows, so there's a risk right there.  Before I go down that route, do you know what versions of node and gulp you're using?

**Comment by bduff9** [comment]
Oh, I'm sorry.  I didn't see anywhere on npm or here where it wasn't supported for Windows.  I am using node 4.4.6 and gulp 3.9.1

**Comment by hounshell** [comment]
Windows should be fine. I haven't tried it myself (no machine) but I think I was fairly defensive when I built it so paths should be fine. 

The node version is the problem. According to http://node.green support for that was added in 6.8.1. Is upgrading a possibility?

If you can, let me know if you see any other weird issues.

**Comment by bduff9** [comment]
Thanks for your reply, it definitely was the node version as updating to the latest versions of npm and node allowed me to run a file where I was bringing in this plugin.

However, once I got that going I began writing the gulp task to actually do the compiling.  To keep it simple, I am currently running this by itself as a gulp task from cmd right now, though eventually it will need to be part of a larger node script.  When I run this currently, I get a javac error, that looks like it is corrupting the path somehow?  The file it is referencing does exist in the correct spot so I'm not sure what is happening in between the gulp.src and the javac lines.  FWIW, I have tried this with both 1 forward slash as well as 2 backslashes, as well as paths starting with `C:` and just `/`, and the errors are identical.

The task I am running is this:
```
const compileMrcapps = function() {
  return gulp.src('/build-test/mrcapps/src/**/*.java')
    .pipe(javac('mrcapps.jar')
      .addLibraries('/build-test/tomcat/lib/**/*.jar')
      .addLibraries('/build-test/m-power_dist/mrcjava/WEB-INF/lib/**/*.jar'))
    .pipe(gulp.dest('out'));
};
```

The error I am getting is this:
```
$ gulp compile-mrcapps
[12:02:40] Requiring external module babel-register
[12:02:41] Using gulpfile C:\mpower-build\gulpfile.babel.js
[12:02:41] Starting 'compile-mrcapps'...
[12:02:43] javac: javac: file not found: Cuild-testmrcappssrcCheckUpdate.java
[12:02:43] javac:
[12:02:43] javac: Usage: javac <options> <source files>
[12:02:43] javac: use -help for a list of possible options
[12:02:43] javac:

C:\mpower-build\node_modules\gulp-javac\javac.js:132
                  throw new gutil.PluginError('gulp-javac', 'javac failed');
                  ^
Error: javac failed
```

**Comment by hounshell** [comment]
Can you get a detailed log by turning tracing on? https://www.npmjs.com/package/gulp-javac#trace

**Comment by hounshell** [comment]
You will probably also see an argument file path and a source file path in that output. The contents of those files would help too, but there's a chance they've been cleaned up automatically.

**Comment by bduff9** [comment]
OK so that did help illuminate something I saw yesterday after I wrote here...

I found the gulp-slash add-on and tried that.  It still failed but it failed in a weird spot, in a temp location that I am not familiar with since it is not a location I put anywhere in my code.  Now I can see that without the plugin, all paths are using backslashes (\) which seems to be an issue, however after the gulp-slash plugin, all paths use the forward slash (/) except this temp location, which is why is fails earlier without the plugin but still fails on this temp location with the plugin.

My guess is that this temp location is where the plugin is storing something (I see both a source and an argument temp location like you mentioned above) and however the code is generating the path ends up failing due to these backslashes.

Since it doesn't matter which way I enter the slashes in my paths and paths work in all my other code, is it possible this javac plugin is mishandling the paths for Windows?  I will eventually need to deploy this to both Windows and Linux machines.  I have included the end of my trace logs as there are many, many files so the earlier part is not that interesting.  Any help you can provide would be appreciated.

```
[08:49:39] javac: Source file: C:\build-test\mrcapps\src\com\mrc\http\security\sso\SSOProfile.java
[08:49:39] javac: Source file: C:\build-test\mrcapps\src\com\mrc\http\security\sso\TripleDES.java
[08:49:39] javac: Source file: C:\build-test\mrcapps\src\com\mrc\http\security\sso\UserSessionStore.java
[08:49:39] javac: Source File Path: C:\Users\Duffey\AppData\Local\Temp\tmp-9704dHgPHeECA9jb.tmp
[08:49:39] javac: Argument File Path: C:\Users\Duffey\AppData\Local\Temp\tmp-9704rqT6pzP2cU0J.tmp
[08:49:39] javac: javac Executing: javac
[08:49:40] javac: javac: file not found: Cuild-testmrcappssrcCheckUpdate.java
[08:49:40] javac:
[08:49:40] javac: Usage: javac <options> <source files>
[08:49:40] javac: use -help for a list of possible options
[08:49:40] javac:
[08:49:40] javac: javac javac complete; code: 2

C:\mpower-build\node_modules\gulp-javac\javac.js:132
                  throw new gutil.PluginError('gulp-javac', 'javac failed');
                  ^
Error: javac failed
```

**Comment by bduff9** [comment]
Hi there!  So when I didn't hear back from you for a couple days I decided to poke around myself and was able to solve the issue.  I will put together a PR for you to look at when I have a second.  However, for now, this gets me past the path issue.

I have another question however, that I cannot find the answer to in the docs, so instead of crowding this issue, I will go ahead and open another.  Feel free to close this or keep it open until you are able to review my PR.  Thanks

**Comment by hounshell** [comment]
Sorry, holiday season is taking it's toll on me.  I'm glad you were able to find the problem though.  I'll keep this open until I see the PR.

**Comment by hounshell** [comment]
PR merged.

**Comment by hounshell** [comment]
This has been published.

Also just so you know, I need to reorganize my repositories a bit (for private reasons).  This repository will be going away and everything will (hopefully) move to [/hounshell/gulp-compilers](https://github.com/hounshell/gulp-compilers). I need to do the takedown soon, and it'll take a while to get the new one up.  The package will still be available on npm, and I'll keep developing on it. I'll be watching the new repo for issues.

Thanks again for the PR.
